---
- hosts: all
  become: yes
  tasks:
  - debug:
      msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}

  - debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    when: ansible_default_ipv4.gateway is defined

  - debug:
      var: play_hosts

  - debug:
      msg: "^{{ hostvars[item]['ansible_default_ipv4']['address'] | regex_escape() }} {{ item }}"
    with_items: "{{ play_hosts }}"
