- hosts: k3s_worker
  gather_facts: no
  tasks:
  - name: "Allow cni0 in"
    ufw:
      comment: "cni0 in"
      rule: allow
      interface: cni0
      direction: in
      from_ip: "10.42.0.0/16"
      to_ip: "127.0.0.1"
      #delete: yes

  - name: "Allow k3s DNS in"
    ufw:
      comment: "k3s DNS in"
      rule: allow
      direction: in
      to_ip: "10.43.0.0/16"
      to_port: 53
      #delete: yes
  - name: "Allow k3s DNS out"
    ufw:
      comment: "k3s DNS out"
      rule: allow
      direction: out
      to_ip: "10.43.0.0/16"
      to_port: 53
      #delete: yes
  - name: "Allow route DNS"
    ufw:
      comment: "route DNS"
      rule: allow
      route: yes
      to_port: 53
      #delete: yes

  - name: "Allow k3s coredns Liveness probe in"
    ufw:
      comment: "k3s coredns Liveness probe"
      rule: allow
      direction: in
      to_ip: "10.42.1.11"
      to_port: 8080
      proto: tcp
      delete: yes
  - name: "Allow k3s coredns Liveness probe out"
    ufw:
      comment: "k3s coredns Liveness probe"
      rule: allow
      direction: out
      to_ip: "10.42.1.11"
      to_port: 8080
      proto: tcp
      delete: yes
  - name: "Allow k3s coredns Liveness probe in"
    ufw:
      comment: "k3s coredns Liveness probe"
      rule: allow
      direction: in
      to_ip: "10.42.0.0/16"
      to_port: 8080
      proto: tcp
      #delete: yes
  - name: "Allow k3s coredns Liveness probe out"
    ufw:
      comment: "k3s coredns Liveness probe"
      rule: allow
      direction: out
      to_ip: "10.42.0.0/16"
      to_port: 8080
      proto: tcp
      #delete: yes
  - name: "Allow route 8080/tcp"
    ufw:
      comment: "route 8080/tcp"
      rule: allow
      route: yes
      to_port: 8080
      proto: tcp
      #delete: yes

  - name: "Allow k3s coredns kubernetes in"
    ufw:
      comment: "k3s coredns kubernetes"
      rule: allow
      direction: in
      to_ip: "10.43.0.1"
      to_port: "443"
      proto: tcp
      delete: yes
  - name: "Allow k3s coredns kubernetes out"
    ufw:
      comment: "k3s coredns kubernetes"
      rule: allow
      direction: out
      to_ip: "10.43.0.1"
      to_port: "443"
      proto: tcp
      delete: yes
  - name: "Allow k3s coredns kubernetes in"
    ufw:
      comment: "k3s coredns kubernetes"
      rule: allow
      direction: in
      to_ip: "10.43.0.0/16"
      to_port: "443"
      proto: tcp
      #delete: yes
  - name: "Allow k3s coredns kubernetes out"
    ufw:
      comment: "k3s coredns kubernetes"
      rule: allow
      direction: out
      to_ip: "10.43.0.0/16"
      to_port: "443"
      proto: tcp
      #delete: yes

  - name: "Allow route HTTPS"
    ufw:
      comment: "route HTTPS"
      rule: allow
      route: yes
      to_port: 443
      proto: tcp
      #delete: yes

  - name: "Allow route HTTP"
    ufw:
      comment: "route HTTP"
      rule: allow
      route: yes
      to_port: 80
      proto: tcp
      #delete: yes
